name: CI

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: cd client && npm install
      - name: run tests
        run: npm run test
