version: '3'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile-dev
    container_name: todo-backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
    - dynamodb-local

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile-dev
    container_name: todo-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"

volumes:
  dynamodb-data: