name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Checkout code
        uses: actions/checkout@v3

      - name: install packages
        run: cd frontend && npm install

      - name: lint code
        run: npm run lint

      - name: run tests
        run: npm run test

      - name: create badge
        run: npm run coverage:badge

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add: ./frontend/README.md
          new_branch: ${{ github.event.pull_request.head.ref }}
          committer_name: Github Actions
          committer_email: actions@github.com
          message: "Updates readme with test coverage"

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: install packages
        run: cd backend && pip install poetry && poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

      - name: lint code
        run: poetry run black --check .

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile-dev
          push: false
          tags: jackreichert/over-engineered-todo:${{ github.sha }}

      - name: Build frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile-dev
          push: false
          tags: jackreichert/over-engineered-todo:${{ github.sha }}
