name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install packages
        run: cd client && npm install

      - name: lint code
        run: npm run lint

      - name: run tests
        run: npm run test

      - name: create badge
        run: npm run coverage:badge

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          add: ./client/README.md
          new_branch: ${{ github.event.pull_request.head.ref }}
          committer_name: Github Actions
          committer_email: actions@github.com
          message: "Updates readme with test coverage"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build server Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./Dockerfile-dev
          push: false
          tags: jackreichert/over-engineered-todo:${{ github.sha }}
